service: react-chat

plugins:
  - serverless-python-requirements
  - serverless-wsgi

provider:
  name: aws
  runtime: python3.7
  region: us-west-2
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}


package:
  exclude:
    - .env

custom:
  wsgi:
    app: app.app
    packRequirements: false

resources:
  Resources:
    ReactChatSQS:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "react-chat-${opt:stage, 'dev'}"
        VisibilityTimeout: 300
        MessageRetentionPeriod: 60
        RedrivePolicy:
          deadLetterTargetArn:
            "Fn::GetAtt":
              - ReactChatDLQ
              - Arn
          maxReceiveCount: 1

    ReactChatDLQ:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "react-chat-deadletter-queue-${opt:stage, 'dev'}"
        MessageRetentionPeriod: 1209600

functions:
  api:
    handler: wsgi_handler.handler
    timeout: 30
    events:
      - http: ANY /
      - http: "ANY {proxy+}"